__Завдання 1__ \
 Виконати набір вправ. Всі завдання виконати 2 способами: \
а) з використанням універсальних функцій бібліотеки NumPy. \
b) за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо). \
с) для обох випадків порахувати час виконання скрипту та зробити висновки.


In [7]:
import numpy as np
import random
from datetime import datetime
import time

print("Вправа 6_ітеративно")
start_time = datetime.now()
def task06_iterative():
    
    # 1: Запит користувача значень масиву
    array = list(map(int, input("Введіть значення масиву через пробіл: ").split()))

    # 2: Знаходження ненульових елементів в масиві  та заміна їх на -1
    for i in range(len(array)):
        if array[i] != 0:  
            array[i] = -1
    
    # 3: Виведення масиву
    print(array)

# 4: Виклик функції
task06_iterative()
print(datetime.now() - start_time)

print("Вправа 6_numpy")
start_time = datetime.now()
def task06_numpy():
    
    # 1: Запит користувача значень масиву
    m = list(map(int, input("Введіть значення масиву через пробіл: ").split()))
    m = np.array(m)

    # 2: Знаходження ненульових елементів в масиві за умовою, заміна їх на -1
    mod = np.where(m != 0, -1, m)    

    # 3: Друк масиву
    print(mod)

# 4: Виклик функції
task06_numpy()
print(datetime.now() - start_time)

print("Вправа 9_ітеративно")
start_time = datetime.now()
def task09_iterative(n):
    
    # 1: Ітеративне створення масиву від n до 0
    my_array = []
    for i in range(n, -1, -1):
        my_array.append(i)
    
    return my_array

# 2: Запит користувача числа n з клавіатури
n = int(input("Введіть число n: "))

# 3: Вивід результату
print("Створений масив:", task09_iterative(n))
print(datetime.now() - start_time)

print("Вправа 9_numpy")
start_time = datetime.now()
def task09_numpy(n):
    
    # 1: Створення масиву від n до 0 за допомогою функції arange
    my_array = np.arange(n, -1, -1)
    
    return my_array

# 2: Запит користувача числа n з клавіатури
n = int(input("Введіть число n: "))

# 3: Вивід результату
print("Створений масив:", task09_numpy(n))
print(datetime.now() - start_time)

print("Вправа 10_ітеративно")
start_time = datetime.now()
def task10_iterative():
    
    # 1:Запит користувача значеннь n і m
    n = int(input("Введіть значення n: "))
    m = int(input("Введіть значення m: "))

    # 2:Створення масиву розміром n × m і заповнення його випадковими числами
    array = []
    for i in range(n):
        row = []
        for j in range(m):
            row.append(random.random())
        array.append(row)
    print(array)

    # 3:Знайдення мінімального та максимального значень в масиві
    min_value = float('inf')
    max_value = float('-inf')
    for i in range(n):
        for j in range(m):
            if array[i][j] < min_value:
                min_value = array[i][j]
            if array[i][j] > max_value:
                max_value = array[i][j]

    # 4:Обчислення середнього значення
    sum_value = 0
    for i in range(n):
        for j in range(m):
            sum_value += array[i][j]
    mean_value = sum_value / (n * m)

    # 5:Обчислення середньо-квадратичне відхилення
    sum_squared_diff = 0
    for i in range(n):
        for j in range(m):
            diff = array[i][j] - mean_value
            sum_squared_diff += diff ** 2
    std_deviation = (sum_squared_diff / (n * m)) ** 0.5

    # 6:Округлення значеннь до 3 знаків після коми
    mean_value = round(mean_value, 3)
    std_deviation = round(std_deviation, 3)

    # 7:Виведення результатів
    print("Мінімальне значення:", min_value)
    print("Максимальне значення:", max_value)
    print("Середнє значення:", mean_value)
    print("Середньо-квадратичне відхилення:", std_deviation)

# 8 :Виклик функції
task10_iterative()
print(datetime.now() - start_time)

print("Вправа 10_numpy")
start_time = datetime.now()
def task10_numpy():
    
    # 1:Запит користувача значеннь n і m
    n = int(input("Введіть значення n: "))
    m = int(input("Введіть значення m: "))

    # 2:Створення масиву розміром n × m і заповнення його випадковими числами
    array = np.random.rand(n, m)
    print(array)

    # 3:Знайдення мінімального та максимального значень в масиві
    min_value = np.min(array)
    max_value = np.max(array)

    # 4:Обчислення середнього значення
    mean_value = np.mean(array)

    # 5:Обчислення середньо-квадратичне відхилення
    std_deviation = np.std(array)

    # 6:Округлення значеннь до 3 знаків після коми
    min_value = np.round(min_value, 3)
    max_value = np.round(max_value, 3)
    mean_value = np.round(mean_value, 3)
    std_deviation = np.round(std_deviation, 3)

    # 7:Виведення результатів
    print("Мінімальне значення:", min_value)
    print("Максимальне значення:", max_value)
    print("Середнє значення:", mean_value)
    print("Середньо-квадратичне відхилення:", std_deviation)

# 8 :Виклик функції
task10_numpy()
print(datetime.now() - start_time)

print("Вправа 11_ітеративно")
start_time = datetime.now()
def task11_iterative():
    
    # 1:Запит користувача значення n
    n = int(input("Введіть значення n: "))

    # 2:Створення початкової матриці розміром n×n, заповненої одиницями
    matrix = [[1] * n for _ in range(n)]

    # 3:Додавання нульових рядків і стовпців
    expanded_matrix = [[0] * (n + 2) for _ in range(n + 2)]

    for i in range(n):
        for j in range(n):
            expanded_matrix[i + 1][j + 1] = matrix[i][j]

    # 4:Виведення отриманої матриці
    for row in expanded_matrix:
        print(row)

# 5:Виклик функції
task11_iterative()
print(datetime.now() - start_time)

print("Вправа 11_numpy")
start_time = datetime.now()
def task11_numpy():
    
    # 1:Запит користувача значення n
    n = int(input("Введіть значення n: "))

    # 2:Створення початкової матриці розміром n×n, заповненої одиницями
    matrix = np.ones((n, n), dtype=int)

    # 3:Додавання нульових рядків і стовпців
    expanded_matrix = np.pad(matrix, ((1, 1), (1, 1)), mode='constant', constant_values=0)

    # 4:Виведення отриманої матриці
    print(expanded_matrix)

# 5:Виклик функції
task11_numpy()
print(datetime.now() - start_time)

print("Вправа 12_ітеративно")
start_time = datetime.now()
def task12_iterative():
    
    # 1:Запит користувача значення n
    n = int(input("Введіть значення n: "))

    # 2:Створення масиву розміром n×n заповненого одиницями
    frame = [[1] * n for _ in range(n)]

    # 3:Заповнення першого та останнього рядка значеннями 0
    for i in range(n):
        frame[0][i] = 0
        frame[n - 1][i] = 0

    # 4:Заповнення першої та останьої колонки значеннями 0
    for i in range(n):
        frame[i][0] = 0
        frame[i][n - 1] = 0

    # 5:Друк масиву
    print('\n'.join([' '.join(['{:n}'.format(item) for item in row])
      for row in frame]))

# 6:Виклик функції
task12_iterative()
print(datetime.now() - start_time)

print("Вправа 12_numpy")
start_time = datetime.now()
def task12_numpy():
    
    # 1:Запит користувача значення n
    n = int(input("Введіть значення n: "))

    # 2:Створення масиву розміром n×n, заповнений одиницями
    frame = np.ones((n, n), float)

    # 3:Заповнення першого та останнього рядка значеннями 0
    frame[0, :] = 0
    frame[n - 1, :] = 0

    # 4:Заповнення першої та останьої колонки значеннями 0
    frame[:, 0] = 0
    frame[:, n - 1] = 0

    # 5:Друк масиву
    print(frame)

# 6:Виклик функції
task12_numpy()
print(datetime.now() - start_time)

print("Вправа 15_ітеративно")
start_time = datetime.now()
def task15_iterative(n):
    
    # 1:Створення матриці n x n, заповненої одиницями
    matrix = [[1] * n for _ in range(n)]  

    # 2:Перевірка парності стовпця та заміна на 0
    for i in range(n):
        for j in range(n):
            if j % 2 == 0:
                matrix[i][j] = 0

    return matrix

# 3:Виклик функції з розміром матриці 5x5
result_matrix = task15_iterative(5)

# 5:Друк матриці
for row in result_matrix:
    print(row)
print(datetime.now() - start_time)

print("Вправа 15_numpy")
start_time = datetime.now()
def task15_numpy():
    
    # 1:Запит користувача значення n
    n = int(input("Введіть значення n: "))

    # 2:Створення матриці розміром n×n, заповненої нулями
    frame = np.zeros((n, n), int)

    # 3:Заповнення парних стовпців одиницями
    frame[:, 1::2] = 1
    
    # 5:Друк матриці
    print(frame)

# 6:Виклик функції
task15_numpy()
print(datetime.now() - start_time)

print("Вправа 18_ітеративно")
start_time = datetime.now()
def task18_iterative(n):
    
    # 1:Генерування вектору з n випадкових чисел в діапазоні від 0 до 99
    random_vector = [random.randint(0, 99) for _ in range(n)]

    # 2:Використання множини для знаходження унікальних чисел
    unique_numbers = set(random_vector)

    # 3:Кількість унікальних чисел
    count_unique = len(unique_numbers)

    return count_unique, random_vector

# 4:Виклик функції з розміром вектора 30
n = 30
count, vector = task18_iterative(n)
# 5:Друк результатів
print(f"В послідовності: {vector}")
print(f"{count} - унікальних чисел")
print(datetime.now() - start_time)

print("Вправа 18_numpy")
start_time = datetime.now()
def task18_numpy(n):
    
    # 1:Генерування вектору з n випадкових чисел в діапазоні від 0 до 99
    random_vector = np.random.randint(0, 100, n)

    # 2:Знаходження унікальних чисел та їх кількості
    unique_numbers, count_unique = np.unique(random_vector, return_counts=True)

    return len(unique_numbers), random_vector

# 3:Виклик функції з розміром вектора 30
n = 30
count, vector = task18_iterative(n)
# 4:Друк результатів
print(f"В послідовності: {vector}")
print(f"{count} - унікальних чисел")
print(datetime.now() - start_time)

print("Вправа 19_ітеративно")
start_time = datetime.now()
def task19_iterative(n):
    
    # 1: ніціалізація порожнього списоку для зберігання значень
    vector = []

    # 2:Розміщення n елементів на інтервалі (0, 1)
    for i in range(1, n + 1):
        value = i / (n + 1)
        # 3:Закруглення значення до 3 знаків після коми
        rounded_value = round(value, 3)
        vector.append(rounded_value)

    return vector

# 4:Виклик функції з розміром вектора 10
n = 10
result_vector = task19_iterative(n)

# 5:Друк результатів
print(f"Згенерований вектор: {result_vector}")
print(datetime.now() - start_time)

print("Вправа 19_numpy")
start_time = datetime.now()
def task19_numpy(n):
    
    # 1: Генерація вектору з n елементів на інтервалі (0, 1)
    vector = np.linspace(0, 1, n+1, endpoint=False)[1:]

    # 2: Закруглення значення до 3 знаків після коми
    rounded_vector = np.round(vector, 3)

    return rounded_vector

# 3: Виклик функції з розміром вектора 10
n = 10
result_vector = task19_numpy(n)
# 4:Друк результатів
print(f"Згенерований вектор: {result_vector}")
print(datetime.now() - start_time)

print("Вправа 21_ітеративно")
start_time = datetime.now()
def task21_iterative():
    
    # 1:Запит користувача значень n і m
    n = int(input("Введіть значення n: "))
    m = int(input("Введіть значення m: "))

    # 2:Створення порожньої матриці
    matrix = [[0] * n for _ in range(n)]

    # 3:Заповнення матриці випадковими цілими числами
    for i in range(n):
        for j in range(n):
            matrix[i][j] = random.randint(0, m)
    # 4:Виведення матриці
    for row in matrix:
        print(row)

    # 5:Знаходження максимального елемента матриці
    max_element = max(max(row) for row in matrix)

    # 6:Заміна максимальних елементів на протилежні за знаком
    for i in range(n):
        for j in range(n):
            if matrix[i][j] == max_element:
                matrix[i][j] = -matrix[i][j]

    # 7:Виведення матриці
    for row in matrix:
        print(row)

# 8:Виклик функції
task21_iterative()
print(datetime.now() - start_time)

print("Вправа 21_numpy")
start_time = datetime.now()
def task21_numpy():
    
    # 1: Запит користувача значень n і m
    n = int(input("Введіть значення n: "))
    m = int(input("Введіть значення m: "))

    # 2: Генерація матриці випадкових цілих чисел
    matrix = np.random.randint(0, m + 1, size=(n, n))

    # 3: Виведення матриці
    print(matrix)

    # 4: Знаходження максимального елемента матриці
    max_element = np.max(matrix)

    # 5: Заміна максимальних елементів на протилежні за знаком
    matrix[matrix == max_element] *= -1

    # 6: Виведення матриці
    print(matrix)

# 7:Виклик функції
task21_numpy()
print(datetime.now() - start_time)

Вправа 6_ітеративно


Введіть значення масиву через пробіл:  3 4 0 9 7 0 6 0 4 0 3


[-1, -1, 0, -1, -1, 0, -1, 0, -1, 0, -1]
0:00:04.329555
Вправа 6_numpy


Введіть значення масиву через пробіл:  3 4 0 9 7 0 6 0 4 0 3


[-1 -1  0 -1 -1  0 -1  0 -1  0 -1]
0:00:02.589802
Вправа 9_ітеративно


Введіть число n:  4


Створений масив: [4, 3, 2, 1, 0]
0:00:03.889955
Вправа 9_numpy


Введіть число n:  4


Створений масив: [4 3 2 1 0]
0:00:01.120051
Вправа 10_ітеративно


Введіть значення n:  4
Введіть значення m:  4


[[0.9355642007168107, 0.8622255952790936, 0.41746050629721676, 0.36354380681780685], [0.7629940457546507, 0.7443373381350787, 0.19677239848757677, 0.1508212451017692], [0.8887085448048397, 0.5946286329966964, 0.05874565387673136, 0.07703337018204837], [0.731156422221117, 0.40227328354741887, 0.06532971814744826, 0.11459511859335059]]
Мінімальне значення: 0.05874565387673136
Максимальне значення: 0.9355642007168107
Середнє значення: 0.46
Середньо-квадратичне відхилення: 0.316
0:00:03.019843
Вправа 10_numpy


Введіть значення n:  4
Введіть значення m:  4


[[0.86609804 0.47148751 0.43202319 0.3905458 ]
 [0.57331606 0.87778223 0.80818184 0.57844535]
 [0.36326464 0.95455224 0.46097676 0.62681261]
 [0.60499443 0.47515955 0.8686205  0.89650428]]
Мінімальне значення: 0.363
Максимальне значення: 0.955
Середнє значення: 0.641
Середньо-квадратичне відхилення: 0.199
0:00:01.949871
Вправа 11_ітеративно


Введіть значення n:  4


[0, 0, 0, 0, 0, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 0, 0, 0, 0, 0]
0:00:03.630797
Вправа 11_numpy


Введіть значення n:  4


[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]
0:00:01.049261
Вправа 12_ітеративно


Введіть значення n:  4


0 0 0 0
0 1 1 0
0 1 1 0
0 0 0 0
0:00:01.100905
Вправа 12_numpy


Введіть значення n:  4


[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]
0:00:03.589423
Вправа 15_ітеративно
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
0:00:00
Вправа 15_numpy


Введіть значення n:  4


[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]
0:00:01.239680
Вправа 18_ітеративно
В послідовності: [97, 58, 92, 62, 70, 43, 12, 7, 70, 6, 70, 72, 69, 0, 59, 43, 31, 12, 99, 31, 28, 81, 3, 52, 49, 60, 97, 58, 33, 62]
22 - унікальних чисел
0:00:00
Вправа 18_numpy
В послідовності: [47, 69, 11, 82, 10, 88, 59, 20, 18, 19, 28, 54, 33, 50, 35, 18, 56, 34, 12, 84, 53, 86, 75, 28, 77, 69, 44, 94, 1, 27]
27 - унікальних чисел
0:00:00
Вправа 19_ітеративно
Згенерований вектор: [0.091, 0.182, 0.273, 0.364, 0.455, 0.545, 0.636, 0.727, 0.818, 0.909]
0:00:00
Вправа 19_numpy
Згенерований вектор: [0.091 0.182 0.273 0.364 0.455 0.545 0.636 0.727 0.818 0.909]
0:00:00
Вправа 21_ітеративно


Введіть значення n:  4
Введіть значення m:  4


[4, 4, 4, 0]
[1, 1, 4, 3]
[4, 4, 1, 3]
[0, 0, 2, 1]
[-4, -4, -4, 0]
[1, 1, -4, 3]
[-4, -4, 1, 3]
[0, 0, 2, 1]
0:00:05.344835
Вправа 21_numpy


Введіть значення n:  4
Введіть значення m:  4


[[3 2 3 0]
 [4 4 1 1]
 [2 2 1 2]
 [2 2 4 3]]
[[ 3  2  3  0]
 [-4 -4  1  1]
 [ 2  2  1  2]
 [ 2  2 -4  3]]
0:00:03.974952


__Завдання 2.__ \
Розв’язати систему алгебраїчних рівнянь за допомогою формул Крамера і виконати перевірку за допомогою: \
a) матричного множення; \
b) оберненої матриці; \
c) функції numpy.linalg.solve(). \
Порівняти всі рішення за допомогою функції numpy.allclose() \
\begin{cases} 2x_1 + x_3 + 4x_4 = 9 \\ x_1 + 2x_2 + x_3 + x_4 = 8 \\ 2x_1 + x_2 + x_3 + x_4 = 5 \\ x_1 + x_2 + 2x_3 + x_4 = -1 \end{cases}

In [8]:
import numpy as np

def rozwiaz_system(X, y):
    # 1:Знаходимо головний визначник матриці X
    vuzn_golovnii = np.linalg.det(X)

    # 2:Ініціалізуємо список для збереження розв'язків
    rozwiazania = []

    # 3:Розв'язуємо систему рівнянь за допомогою формул Крамера
    for i in range(X.shape[1]):
        # 4:Замінюємо стовпець i матриці X на вектор y
        ai = X.copy()
        ai[:, i] = y

        # 5:Знаходимо визначник нової матриці
        vuzn_i = np.linalg.det(ai)

        # 6:Знаходимо значення невідомої змінної xi
        xi = vuzn_i / vuzn_golovnii

        # 7:Додаємо xi до списку розв'язків
        rozwiazania.append(xi)

    # 8:Перевіряємо отримані значення за допомогою матричного множення
    ax = np.dot(X, rozwiazania)
    if np.allclose(ax, y):
        print("Перевірка за допомогою  матричного множення пройдена.")
    else:
        print("Перевірка за допомогою  матричного множення не пройдена.")

    return rozwiazania

# 9:Вхідні дані
X = np.array([[2, 0, 1, 4],
              [1, 2, -1, 1],
              [2, 1, 1, 1],
              [1, -1, 2, 1]])
y = np.array([9, 8, 5, -1])

# 10:Розв'язуємо систему рівнянь
rozwiazania = rozwiaz_system(X, y)
print("Розв'язок системи алгебраїчних рівнянь за допомогою формул Крамера: ")
print(rozwiazania)

# 11:Перевірка за допомогою оберненої матриці
inverse_k = np.linalg.inv(X)
im_check = np.dot(inverse_k, y)
print("Перевірка за допомогою оберненої матриці:", im_check)

# 12:Перевірка за допомогою функції numpy.linalg.solve()
f_check = np.linalg.solve(X, y)
print("Перевірка за допомогою функції numpy.linalg.solve():", f_check)

# 13:Порівняння з результатом перевірки за допомогою оберненої матриці
is_equal = np.allclose(rozwiazania, im_check)
print("Порівняння з результатом перевірки за допомогою оберненої матриці:", is_equal)

# 14:Порівняння з результатом перевірки за допомогою функції numpy.linalg.solve()
is_equal = np.allclose(rozwiazania, f_check)
print("Порівняння з результатом перевірки за допомогою функції numpy.linalg.solve():", is_equal)

Перевірка за допомогою  матричного множення пройдена.
Розв'язок системи алгебраїчних рівнянь за допомогою формул Крамера: 
[1.0000000000000022, 2.0000000000000004, -1.0000000000000004, 2.0000000000000004]
Перевірка за допомогою оберненої матриці: [ 1.  2. -1.  2.]
Перевірка за допомогою функції numpy.linalg.solve(): [ 1.  2. -1.  2.]
Порівняння з результатом перевірки за допомогою оберненої матриці: True
Порівняння з результатом перевірки за допомогою функції numpy.linalg.solve(): True


__Завдання 3.__ \
Обчислити значення матричного виразу \
а) з використанням універсальних функцій бібліотеки NumPy. \
b) за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо). \
с) для обох випадків порахувати час виконання скрипту та зробити висновок. \
Порівняти всі рішення за допомогою функції numpy.allclose() \
$
2(2A + B) - B(A - B), де A = \begin{bmatrix}
2 & 3 & 1\\\
4 & -1 & 0\\\
0 & 1 & 2
\end{bmatrix}, B = \begin{bmatrix}
9 & 8 & 7\\\
2 & 7 & 3\\\
4 & 3 & 5
\end{bmatrix}
$

In [1]:
import numpy as np
import time

# 1:Обчислюємо значення матричного виразу з використанням універсальних функцій бібліотеки NumPy
def task_num_py(a, b):
    return a @ (2 * a + b) - b @ (a - b)

# 2:Обчислюємо значення матричного виразу за допомогою ітеративних конструкцій та виводимо результат
def task_iterative(a, b):
    print("\nРезультати обрахунків ітеративною функцією:")
    c = []
    for i in range(len(a)):
        row = []
        for j in range(len(a[0])):
            row.append(a[i][j] - b[i][j])
        c.append(row)
    print("\nA - B: ", c)

    d = []
    for i in range(len(b)):
        row = []
        for j in range(len(c[0])):
            s = 0
            for k in range(len(c[0])):
                s += b[i][k] * c[k][j]
            row.append(s)
        d.append(row)
    print("\nB * (A - B): ", d)

    e = []
    for i in range(len(a)):
        row = []
        for j in range(len(a[0])):
            row.append(a[i][j] * 2)
        e.append(row)
    print("\n2 * A: ", e)

    f = []
    for i in range(len(a)):
        row = []
        for j in range(len(a[0])):
            row.append(e[i][j] + b[i][j])
        f.append(row)
    print("\n(2 * A + B): ", f)

    h = []
    for i in range(len(a)):
        row = []
        for j in range(len(a[0])):
            s = 0
            for k in range(len(a[0])):
                s += a[i][k] * f[k][j]
            row.append(s)
        h.append(row)
    print("\nA * (2 * A + B): ", h)

    z = []
    for i in range(len(h)):
        row = []
        for j in range(len(h[0])):
            row.append(h[i][j] - d[i][j])
        z.append(row)
    print("\nКінцевий результат A * (2 * A + B) - B * (A - B): ", z)
    return z

# 3:Вводимо матричні вирази згідно варіанту
A = np.array([[2, 3, 1], [4, -1, 0], [0, 1, 2]])
B = np.array([[9, 8, 7], [2, 7, 3], [4, 3, 5]])

# 4:Виклик та обрахунок часу виконання функції NumPy
start_time = time.perf_counter()
numpyResult = task_num_py(A, B)
end_time = time.perf_counter()
numpy_time = end_time - start_time

# 5::Виклик та обрахунок часу виконання ітеративної функції
start_time = time.perf_counter()
iterativeResult = task_iterative(A, B)
end_time = time.perf_counter()
iterative_time = end_time - start_time

print("\nРезультати обрахунків функцією Numpy:")
print("\nA + B:\n", (A + B))
print("\nA - B:\n", (A - B))
print("\nA * (2 * A + B):\n", A @ (2 * A + B))
print("\nB * (A - B):\n", B @ (A - B))
print("\nКінцевий результат - A * (2 * A + B) - B * (A - B):\n", A @ (2 * A + B) - B @ (A - B))

comparison = np.allclose(numpyResult, iterativeResult)
print(f"\nРезультати обрахунків обома методами співпадають: {comparison}")

print(f"\nЧас виконання обрахунків функціями NumPy: {numpy_time:.6f} секунд")
print(f"Час виконання обрахунків ітеративними функціями: {iterative_time:.6f} секунд")



Результати обрахунків ітеративною функцією:

A - B:  [[-7, -5, -6], [2, -8, -3], [-4, -2, -3]]

B * (A - B):  [[-75, -123, -99], [-12, -72, -42], [-42, -54, -48]]

2 * A:  [[4, 6, 2], [8, -2, 0], [0, 2, 4]]

(2 * A + B):  [[13, 14, 9], [10, 5, 3], [4, 5, 9]]

A * (2 * A + B):  [[60, 48, 36], [42, 51, 33], [18, 15, 21]]

Кінцевий результат A * (2 * A + B) - B * (A - B):  [[135, 171, 135], [54, 123, 75], [60, 69, 69]]

Результати обрахунків функцією Numpy:

A + B:
 [[11 11  8]
 [ 6  6  3]
 [ 4  4  7]]

A - B:
 [[-7 -5 -6]
 [ 2 -8 -3]
 [-4 -2 -3]]

A * (2 * A + B):
 [[60 48 36]
 [42 51 33]
 [18 15 21]]

B * (A - B):
 [[ -75 -123  -99]
 [ -12  -72  -42]
 [ -42  -54  -48]]

Кінцевий результат - A * (2 * A + B) - B * (A - B):
 [[135 171 135]
 [ 54 123  75]
 [ 60  69  69]]

Результати обрахунків співпадають: True

Час виконання обрахунків функціями NumPy: 0.000050 секунд
Час виконання обрахунків ітеративними функціями: 0.000207 секунд
